name: Feature request
description: Suggest an idea
labels: [enhancement]
body:
  - type: textarea
    id: what
    attributes:
      label: What would you like?
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why / what problem does it solve?
